#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Electro
electro_style = [
    "Abstract",
    "Acid",
    "Acid House",
    "Acid Jazz",
    "Alternative Rock",
    "Ambient",
    "Art Rock",
    "Avantgarde",
    "Ballad",
    "Big Beat",
    "Boogie",
    "Breakbeat",
    "Breaks",
    "Broken Beat",
    "Chanson",
    "Contemporary",
    "Contemporary Jazz",
    "Contemporary R&B",
    "Dark Ambient",
    "Darkwave",
    "Dance-pop",
    "Deep House",
    "Disco",
    "Downtempo",
    "Drone",
    "Drum n Bass",
    "Dub",
    "Dub Techno",
    "Dubstep",
    "EBM",
    "Easy Listening",
    "Electro",
    "Electro House",
    "Euro House",
    "Euro-Disco",
    "Eurodance",
    "Europop",
    "Experimental",
    "Folk",
    "Folk Rock",
    "Freestyle",
    "Fusion",
    "Future Jazz",
    "Funk",
    "Gabber",
    "Garage House",
    "Hard House",
    "Hard Trance",
    "Hardcore",
    "Happy Hardcore",
    "Hi NRG",
    "Hip Hop",
    "Hip-House",
    "House",
    "IDM",
    "Indie Pop",
    "Indie Rock",
    "Industrial",
    "Italo House",
    "Italo-Disco",
    "Italodance",
    "Jazz-Funk",
    "Jazzdance",
    "J-pop",
    "Jungle",
    "Krautrock",
    "Leftfield",
    "Latin",
    "Minimal",
    "Modern Classical",
    "New Age",
    "New Beat",
    "New Wave",
    "Noise",
    "Psychedelic Rock",
    "Pop Rap",
    "Pop Rock",
    "Post Rock",
    "Post-Punk",
    "Prog Rock",
    "Progressive House",
    "Progressive Trance",
    "Punk",
    "RnB/Swing",
    "Reggae-Pop",
    "Rhythm & Blues",
    "Score",
    "Soft Rock",
    "Soul",
    "Soundtrack",
    "Tech House",
    "Techno",
    "Theme",
    "Trance",
    "Tribal",
    "Tribal House",
    "Trip Hop",
    "UK Garage",
    "Vocal"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Rock
rock_style = [
    "Abstract",
    "Acoustic",
    "AOR",
    "Alternative Rock",
    "Ambient",
    "Art Rock",
    "Avantgarde",
    "Ballad",
    "Beat",
    "Black Metal",
    "Blues Rock",
    "Britpop",
    "Classic Rock",
    "Contemporary R&B",
    "Country",
    "Country Rock",
    "Doo Wop",
    "Disco",
    "Downtempo",
    "Doom Metal",
    "Electric Blues",
    "Electro",
    "Emo",
    "Experimental",
    "Folk",
    "Folk Rock",
    "Funk",
    "Funk Metal",
    "Garage Rock",
    "Glam",
    "Grindcore",
    "Grunge",
    "Goth Rock",
    "Heavy Metal",
    "Holiday",
    "Indie Pop",
    "Indie Rock",
    "Industrial",
    "Instrumental",
    "Jazz-Funk",
    "Jazz-Rock",
    "Krautrock",
    "Lo-Fi",
    "Leftfield",
    "Lounge",
    "Metalcore",
    "Mod",
    "Modern Classical",
    "Noise",
    "Nu Metal",
    "Post Hardcure",
    "Post Punk",
    "Post Rock",
    "Power Metal",
    "Power Pop",
    "Prog Rock",
    "Progressive Metal",
    "Psychedelic Rock",
    "Punk",
    "Pop Punk",
    "Pop Rap",
    "Pop Rock",
    "Rhythm & Blues",
    "Rockabilly",
    "Shoegaze",
    "Southern Rock",
    "Space Rock",
    "Stoner Rock",
    "Surf",
    "Symphonic Metal",
    "Symphonic Rock",
    "Synth-pop",
    "Theme",
    "Thrash",
    "Vocal"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Pop
pop_list = [
    "Acoustic",
    "Alternative Rock",
    "Anison",
    "Arena Rock",
    "Art Rock",
    "Ballad",
    "Big Band",
    "Blues Rock",
    "Boogie",
    "Bollywood",
    "Bubblegum",
    "Chanson",
    "Classical",
    "Classic Rock",
    "City Pop",
    "Comedy",
    "Contemporary",
    "Contemporary Jazz",
    "Contemporary R&B",
    "Country",
    "Country Rock",
    "Dance-pop",
    "Disco",
    "Doo Wop",
    "Downtempo",
    "Electro",
    "Enka",
    "Euro House",
    "Eurodance",
    "Europop",
    "Experimental",
    "Folk",
    "Folk Rock",
    "Funk",
    "Glam",
    "Garage Rock",
    "Gospel",
    "Holiday",
    "Hip Hop",
    "Hi NRG",
    "Instrumental",
    "Indie Pop",
    "Indie Rock",
    "J-pop",
    "Jazz-Funk",
    "Jazz-Rock",
    "Latin",
    "Latin Jazz",
    "Light Music",
    "Leftfield",
    "Lounge",
    "Modern Classical",
    "MPB",
    "Music Hall",
    "Novelty",
    "Parody",
    "Power Pop",
    "Prog Rock",
    "Psychedelic Rock",
    "Punk",
    "Reggae-Pop",
    "Religious",
    "RnB/Swing",
    "Rock & Roll",
    "Rockabilly",
    "Score",
    "Soft Rock",
    "Soul",
    "Soul-Jazz",
    "Spoken Word",
    "Surf",
    "Swing",
    "Symphonic Rock",
    "Techno",
    "Theme",
    "Trance",
    "Trip Hop",
    "Vocal"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Funk Soul
funk_soul_style = [
    "Acid Jazz",
    "Acoustic",
    "Afro-Cuban",
    "Afrobeat",
    "Alternative Rock",
    "Ballad",
    "Bayou Funk",
    "Big Band",
    "Blues Rock",
    "Boogie",
    "Bossa Nova",
    "Breakbeat",
    "Breaks",
    "Chanson",
    "City Pop",
    "Classic Rock",
    "Compas",
    "Contemporary Jazz",
    "Contemporary R&B",
    "Conscious",
    "Country",
    "Country Rock",
    "Deep House",
    "Disco",
    "Downtempo",
    "Dance-pop",
    "Electro",
    "Electro Funk",
    "Experimental",
    "Folk",
    "Folk Rock",
    "Funk",
    "Fusion",
    "Glam",
    "Garage Rock",
    "Garage House",
    "Gospel",
    "Holiday",
    "Hip Hop",
    "House",
    "Indie Rock",
    "Instrumental",
    "Italo-Disco",
    "Jazz-Funk",
    "Jazz-Rock",
    "Jazzdance",
    "Jazzy Hip-Hop",
    "J-pop",
    "Latin",
    "Latin Jazz",
    "Leftfield",
    "Minimalist Funk",
    "Modern Soul",
    "Neo Soul",
    "New Jack Swing",
    "New Wave",
    "P.Funk",
    "Psychedelic",
    "Psychedelic Rock",
    "Pop Rap",
    "Pop Rock",
    "Reggae",
    "Reggae-Pop",
    "RnB/Swing",
    "Rock & Roll",
    "Smooth Jazz",
    "Soul",
    "Soul-Jazz",
    "Swing",
    "Swingbeat",
    "Ska",
    "Surf",
    "Techno",
    "Theme",
    "Trip Hop",
    "Vocal"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Jazz
jazz_style = [
    "Acid Jazz",
    "Acoustic",
    "Afro-Cuban",
    "Afro-Cuban Jazz",
    "Afrobeat",
    "Alternative Rock",
    "Ambient",
    "Art Rock",
    "Avant-garde Jazz",
    "Avantgarde",
    "Ballad",
    "Big Band",
    "Blues Rock",
    "Bossa Nova",
    "Bossanova",
    "Bop",
    "Broken Beat",
    "Cha-Cha",
    "Chanson",
    "Classic Rock",
    "Classical",
    "Contemporary",
    "Contemporary Jazz",
    "Contemporary R&B",
    "Cool Jazz",
    "Country",
    "Country Rock",
    "Deep House",
    "Dixieland",
    "Disco",
    "Downtempo",
    "Electro",
    "Experimental",
    "Folk",
    "Folk Rock",
    "Free Improvisation",
    "Free Jazz",
    "Fusion",
    "Gypsy Jazz",
    "Hard Bop",
    "Hip Hop",
    "Holiday",
    "House",
    "Indie Rock",
    "Instrumental",
    "Jazz-Funk",
    "Jazz-Rock",
    "Jazzdance",
    "Latin",
    "Latin Jazz",
    "Light Music",
    "Lounge",
    "Modal",
    "Modern",
    "Modern Classical",
    "MPB",
    "Mambo",
    "Modal",
    "Musical",
    "Neo Soul",
    "New Age",
    "New Wave",
    "Piano Blues",
    "Pop Rock",
    "Post Bop",
    "Prog Rock",
    "Ragtime",
    "Rumba",
    "Rhythm & Blues",
    "Rock & Roll",
    "Salsa",
    "Schlager",
    "Score",
    "Smooth Jazz",
    "Samba",
    "Soul",
    "Soul-Jazz",
    "Space-Age",
    "Spoken Word",
    "Synth-pop",
    "Swing",
    "Synth-pop",
    "Theme",
    "Tango",
    "Trip Hop"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Folk
world_style = [
    "Acoustic",
    "Afro-Cuban",
    "Afrobeat",
    "African",
    "Alternative Rock",
    "Art Rock",
    "Avantgarde",
    "Ballad",
    "Bluegrass",
    "Blues Rock",
    "Bolero",
    "Bollywood",
    "Calypso",
    "Cajun",
    "Celtic",
    "Chanson",
    "Choral",
    "Classic Rock",
    "Classical",
    "Contemporary",
    "Contemporary Jazz",
    "Country",
    "Country Blues",
    "Country Rock",
    "Cumbia",
    "Disco",
    "Downtempo",
    "Dub",
    "Easy Listening",
    "Éntekhno",
    "Experimental",
    "Fado",
    "Field Recording",
    "Flamenco",
    "Folk",
    "Folk Rock",
    "Fusion",
    "Gospel",
    "Hawaiian",
    "Highlife",
    "Honky Tonk",
    "Indian Classical",
    "Indie Pop",
    "Indie Rock",
    "Instrumental",
    "Jazz-Rock",
    "Kayōkyoku",
    "Latin Jazz",
    "Laïkó",
    "MPB",
    "Modern Classical",
    "Neofolk",
    "New Age",
    "Nordic",
    "Pacific",
    "Polka",
    "Political",
    "Prog Rock",
    "Psychedelic",
    "Psychedelic Rock",
    "Reggae",
    "Religious",
    "Rebetiko",
    "Rhythm & Blues",
    "Rock & Roll",
    "Rockabilly",
    "Romantic",
    "Romani",
    "Rumba",
    "Samba",
    "Score",
    "Schlager",
    "Soul",
    "Soukous",
    "Southern Rock",
    "Spoken Word",
    "Swing",
    "Synth-pop",
    "Tango",
    "Theme",
    "Tribal",
    "Zydeco",
    "Zouk"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Classical
classical_style = [
    "Acoustic",
    "Ambient",
    "Anison",
    "Art Rock",
    "Avant-garde Jazz",
    "Avantgarde",
    "Ballad",
    "Baroque",
    "Ballet",
    "Big Band",
    "Blues Rock",
    "Brass Band",
    "Canzone Napoletana",
    "Chanson",
    "Choral",
    "Classic Rock",
    "Classical",
    "Contemporary",
    "Contemporary Jazz",
    "Cool Jazz",
    "Country",
    "Dialogue",
    "Disco",
    "Drone",
    "Downtempo",
    "Early",
    "Education",
    "Electro",
    "Experimental",
    "Field Recording",
    "Folk",
    "Folk Rock",
    "Free Improvisation",
    "Free Jazz",
    "Fusion",
    "Gospel",
    "Holiday",
    "House",
    "Impressionist",
    "Instrumental",
    "Jazz-Rock",
    "Light Music",
    "Marches",
    "Medieval",
    "Minimal",
    "Modern",
    "Modern Classical",
    "Musical",
    "Musique Concrète",
    "Neo-Classical",
    "Neo-Romantic",
    "New Age",
    "Opera",
    "Operetta",
    "Oratorio",
    "Post-Modern",
    "Polka",
    "Pop Rock",
    "Political",
    "Prog Rock",
    "Religious",
    "Rock & Roll",
    "Romantic",
    "Score",
    "Smooth Jazz",
    "Soft Rock",
    "Spoken Word",
    "Story",
    "Swing",
    "Symphonic Rock",
    "Tango",
    "Theme",
    "Technical",
    "Twelve-tone",
    "Video Game Music",
    "Volksmusik",
    "Vocal",
    "Zarzuela",
    "Zydeco"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Hip hop
hip_hop_style = [
    "Acid House",
    "Acid Jazz",
    "Alternative Rock",
    "Ambient",
    "Abstract",
    "Bass Music",
    "Big Beat",
    "Blues Rock",
    "Boom Bap",
    "Bounce",
    "Breakbeat",
    "Breaks",
    "Broken Beat",
    "Chanson",
    "Classic Rock",
    "Cloud Rap",
    "Conscious",
    "Contemporary Jazz",
    "Contemporary R&B",
    "Dance-pop",
    "Dancehall",
    "Deep House",
    "DJ Battle Tool",
    "Disco",
    "Dub",
    "Dubstep",
    "Electro",
    "Electro House",
    "Electro-Pop",
    "Experimental",
    "Euro House",
    "Europop",
    "Freestyle",
    "Funk",
    "Funk Metal",
    "G-Funk",
    "Gangsta",
    "Go-Go",
    "Grime",
    "Hard Rock",
    "Hardcore",
    "Hardcore Hip-Hop",
    "Hip Hop",
    "Hip-House",
    "Indie Pop",
    "Indie Rock",
    "Instrumental",
    "IDM",
    "J-pop",
    "Jazz-Funk",
    "Jazzdance",
    "Jazzy Hip-Hop",
    "Latin",
    "Leftfield",
    "Miami Bass",
    "Minimal",
    "New Jack Swing",
    "New Wave",
    "Nu Metal",
    "P.Funk",
    "Pop Rock",
    "Pop Rap",
    "Punk",
    "Progressive House",
    "Reggae",
    "Reggae-Pop",
    "Reggaeton",
    "Rhythm & Blues",
    "Ragga",
    "Ragga HipHop",
    "Soul",
    "Soul-Jazz",
    "Synth-pop",
    "Thug Rap",
    "Trap",
    "Techno",
    "Trance",
    "Turntablism",
    "UK Garage",
    "Vocal",
    "Whisper Rap"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Stage&screen
stage_style = [
    "Abstract",
    "Acoustic",
    "Alternative Rock",
    "Ambient",
    "Art Rock",
    "Avantgarde",
    "Ballad",
    "Baroque",
    "Beat",
    "Big Band",
    "Blues Rock",
    "Bollywood",
    "Bossa Nova",
    "Chanson",
    "Classic Rock",
    "Classical",
    "Comedy",
    "Contemporary",
    "Contemporary Jazz",
    "Contemporary R&B",
    "Country",
    "Country Rock",
    "Dance-pop",
    "Dialogue",
    "Disco",
    "Downtempo",
    "Electro",
    "Electro House",
    "Experimental",
    "Folk",
    "Folk Rock",
    "Fusion",
    "Gospel",
    "Hard Rock",
    "Heavy Metal",
    "Hip Hop",
    "Hindustani",
    "Holiday",
    "Indie Rock",
    "Instrumental",
    "Jazz-Funk",
    "Jazz-Rock",
    "Lounge",
    "Light Music",
    "Latin Jazz",
    "Minimal",
    "Modern",
    "Modern Classical",
    "Music Hall",
    "Musical",
    "Neo-Classical",
    "Neo-Romantic",
    "New Age",
    "New Wave",
    "Opera",
    "Operetta",
    "Psychedelic",
    "Psychedelic Rock",
    "Pop Rap",
    "Pop Rock",
    "Prog Rock",
    "RnB/Swing",
    "Rock & Roll",
    "Romantic",
    "Score",
    "Schlager",
    "Smooth Jazz",
    "Soul",
    "Soul-Jazz",
    "Spoken Word",
    "Story",
    "Surf",
    "Synth-pop",
    "Techno",
    "Theme",
    "Video Game Music"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Latin
latin_style = [
    "Acoustic",
    "Afro-Cuban",
    "Afro-Cuban Jazz",
    "Afrobeat",
    "Alternative Rock",
    "Axé",
    "Ballad",
    "Bachata",
    "Beat",
    "Big Band",
    "Bolero",
    "Bossanova",
    "Bossa Nova",
    "Blues Rock",
    "Calypso",
    "Cha-Cha",
    "Charanga",
    "Classic Rock",
    "Compas",
    "Contemporary Jazz",
    "Contemporary R&B",
    "Corrido",
    "Cumbia",
    "Cubano",
    "Dance-pop",
    "Descarga",
    "Disco",
    "Downtempo",
    "Electro",
    "Experimental",
    "Europop",
    "Folk",
    "Folk Rock",
    "Fusion",
    "Forró",
    "Funk",
    "Guaguancó",
    "Guaracha",
    "House",
    "Instrumental",
    "Jazz-Funk",
    "Jazz-Rock",
    "Lambada",
    "Latin",
    "Latin Jazz",
    "Latin Pop",
    "Mambo",
    "Mariachi",
    "Merengue",
    "MPB",
    "Norteño",
    "Nueva Cancion",
    "Pop Rap",
    "Pop Rock",
    "Pachanga",
    "Polka",
    "Porro",
    "Prog Rock",
    "Reggae",
    "Reggaeton",
    "Ranchera",
    "Rhythm & Blues",
    "Rumba",
    "Salsa",
    "Schlager",
    "Son",
    "Son Montuno",
    "Smooth Jazz",
    "Ska",
    "Swing",
    "Tango",
    "Tejano",
    "Theme",
    "Vallenato",
    "Vocal"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Reagge
reggae_style = [
    "Acid Jazz",
    "Afro-Cuban",
    "Afrobeat",
    "Alternative Rock",
    "Ambient",
    "Ballad",
    "Big Beat",
    "Blues Rock",
    "Breakbeat",
    "Breaks",
    "Calypso",
    "Classic Rock",
    "Conscious",
    "Contemporary Jazz",
    "Contemporary R&B",
    "Country",
    "Country Rock",
    "Dance-pop",
    "Dancehall",
    "Deep House",
    "Disco",
    "Downtempo",
    "Dub",
    "Dub Poetry",
    "Dubstep",
    "Electro",
    "Euro House",
    "Eurodance",
    "Experimental",
    "Folk",
    "Folk Rock",
    "Fusion",
    "Glam",
    "Gangsta",
    "Gospel",
    "Hard Rock",
    "Hardcore",
    "Hip Hop",
    "Hip-House",
    "House",
    "Indie Rock",
    "Instrumental",
    "J-pop",
    "Jazz-Funk",
    "Jungle",
    "Latin",
    "Latin Jazz",
    "Mento",
    "MPB",
    "New Wave",
    "Psychedelic Rock",
    "Pop Rap",
    "Pop Rock",
    "Prog Rock",
    "Reggae",
    "Reggae Gospel",
    "Reggae-Pop",
    "Reggaeton",
    "Ragga",
    "Ragga HipHop",
    "Rhythm & Blues",
    "Rock & Roll",
    "Roots Reggae",
    "Salsa",
    "Samba",
    "Ska",
    "Soft Rock",
    "Soul",
    "Soul-Jazz",
    "Steel Band",
    "Synth-pop",
    "Toasting",
    "Tribal",
    "Trance",
    "UK Garage",
    "Vocal",
    "Zouk"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Blues
blues_style = [
    "Acid Rock",
    "Acoustic",
    "AOR",
    "Alternative Rock",
    "Ambient",
    "Art Rock",
    "Avantgarde",
    "Ballad",
    "Bayou Funk",
    "Big Band",
    "Blues Rock",
    "Boogie Woogie",
    "Chanson",
    "Chicago Blues",
    "Classic Rock",
    "Cool Jazz",
    "Contemporary Jazz",
    "Contemporary R&B",
    "Country",
    "Country Blues",
    "Country Rock",
    "Delta Blues",
    "Disco",
    "Dixieland",
    "Doo Wop",
    "Downtempo",
    "Electric Blues",
    "Experimental",
    "Folk",
    "Folk Rock",
    "Funk",
    "Fusion",
    "Glam",
    "Garage Rock",
    "Gospel",
    "Hard Bop",
    "Hard Rock",
    "Harmonica Blues",
    "Holiday",
    "Indie Rock",
    "Instrumental",
    "Jazz-Funk",
    "Jazz-Rock",
    "Louisiana Blues",
    "Memphis Blues",
    "Modern Electric Blues",
    "Neo Soul",
    "New Wave",
    "Piedmont Blues",
    "Piano Blues",
    "Pop Rap",
    "Pop Rock",
    "Prog Rock",
    "Pub Rock",
    "Punk",
    "Reggae",
    "Rock & Roll",
    "Rockabilly",
    "Schlager",
    "Score",
    "Smooth Jazz",
    "Southern Rock",
    "Soul",
    "Soul-Jazz",
    "Spoken Word",
    "Stoner Rock",
    "Surf",
    "Swing",
    "Texas Blues",
    "Theme",
    "Zydeco"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Non music
non_music_style = [
    "Abstract",
    "African",
    "Alternative Rock",
    "Anison",
    "Art Rock",
    "Audiobook",
    "Ballad",
    "Baroque",
    "Beat",
    "Big Band",
    "Blues Rock",
    "Chanson",
    "Classic Rock",
    "Comedy",
    "Contemporary",
    "Contemporary Jazz",
    "Country",
    "Country Rock",
    "Dialogue",
    "Drone",
    "Education",
    "Electro",
    "Erotic",
    "Experimental",
    "Field Recording",
    "Folk",
    "Folk Rock",
    "Free Improvisation",
    "Free Jazz",
    "Gospel",
    "Hard Rock",
    "Health-Fitness",
    "Holiday",
    "Indie Rock",
    "Industrial",
    "Interview",
    "Jazz-Funk",
    "Leftfield",
    "Minimal",
    "Modern",
    "Modern Classical",
    "Movie Effects",
    "Musical",
    "Musique Concrète",
    "Noise",
    "Novelty",
    "Opera",
    "Parody",
    "Political",
    "Poetry",
    "Prog Rock",
    "Public Broadcast",
    "Punk",
    "Pop Rap",
    "Radioplay",
    "Religious",
    "Rhythm & Blues",
    "Rock & Roll",
    "Romantic",
    "Score",
    "Sermon",
    "Silent",
    "Sound Art",
    "Sound Poetry",
    "Special Effects",
    "Speech",
    "Spoken Word",
    "Story",
    "Surf",
    "Techno",
    "Theme",
    "Therapy",
    "Vocal",
    "Wedding",
    "Zumba"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>children
children_style = [
    "Abstract",
    "Acoustic",
    "African",
    "Alternative Rock",
    "Anison",
    "Art Rock",
    "Audiobook",
    "Ballad",
    "Baroque",
    "Beat",
    "Big Band",
    "Blues Rock",
    "Bubblegum",
    "Catalan Music",
    "Chanson",
    "Choral",
    "Classic Rock",
    "Comedy",
    "Contemporary",
    "Contemporary Jazz",
    "Contemporary R&B",
    "Country",
    "Country Rock",
    "Dance-pop",
    "Dialogue",
    "Disco",
    "Downtempo",
    "Education",
    "Educational",
    "Electro",
    "Experimental",
    "Field Recording",
    "Folk",
    "Folk Rock",
    "Gospel",
    "Health-Fitness",
    "Holiday",
    "Indie Rock",
    "Instrumental",
    "Italo-Disco",
    "J-pop",
    "Karaoke",
    "Kayōkyoku",
    "Light Music",
    "Modern",
    "MPB",
    "Marches",
    "Movie Effects",
    "Music Hall",
    "New Wave",
    "Novelty",
    "Opera",
    "Parody",
    "Piano Blues",
    "Polka",
    "Pop Punk",
    "Pop Rap",
    "Political",
    "Progressive Rock",
    "Promotional",
    "Punk",
    "Radioplay",
    "Religious",
    "RnB/Swing",
    "Rock & Roll",
    "Romantic",
    "Samba",
    "Score",
    "Special Effects",
    "Speech",
    "Spoken Word",
    "Soft Rock",
    "Soul",
    "Swing",
    "Techno",
    "Theme",
    "Therapy",
    "Vocal",
    "Volksmusik"
]

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Brass
military_style = [
    "Ambient",
    "Alternative Rock",
    "Ballad",
    "Baroque",
    "Big Band",
    "Blues Rock",
    "Brass Band",
    "Celtic",
    "Cha-Cha",
    "Chanson",
    "Choral",
    "Classical",
    "Comedy",
    "Contemporary",
    "Contemporary Jazz",
    "Country",
    "Country Blues",
    "Country Rock",
    "Dark Ambient",
    "Disco",
    "Dixieland",
    "Downtempo",
    "Dub",
    "Electro",
    "Experimental",
    "Field Recording",
    "Flamenco",
    "Folk",
    "Folk Rock",
    "Funk",
    "Gospel",
    "Gypsy Jazz",
    "Holiday",
    "Hard Rock",
    "Industrial",
    "Instrumental",
    "Jazz-Funk",
    "Jazz-Rock",
    "Latin Jazz",
    "Light Music",
    "Marches",
    "Mambo",
    "Military",
    "Modern",
    "Modern Classical",
    "Music Hall",
    "Neofolk",
    "Neo-Classical",
    "Neo-Romantic",
    "Novelty",
    "Opera",
    "Operetta",
    "Pasodoble",
    "Political",
    "Polka",
    "Promotional",
    "Punk",
    "Ragtime",
    "Religious",
    "Reggae",
    "Renaissance",
    "Rhythm & Blues",
    "Rock & Roll",
    "Rockabilly",
    "Romani",
    "Romantic",
    "Rumba",
    "Samba",
    "Score",
    "Sea Shanties",
    "Special Effects",
    "Soul",
    "Soul-Jazz",
    "Speech",
    "Spoken Word",
    "Synth-pop",
    "Tango",
    "Theme",
    "Vocal",
    "Volksmusik",
    "Western"
]


print("list_styles.py loaded successfully")